eureka:
  client:
    service-url:
      default-zone: http://localhost:8761

  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int}

server:
  port: 8090

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      routes:
        - id: service-server
          uri: lb://service-server
          predicates:
            - name: Path
              args:
                patterns: /service/**
#        - id: aws-gateway
#          uri: https://serverless.domain.com
#          predicates:
#            - name: Path
#              args:
#                patterns: /server-less/**


