eureka:
  client:
    service-url:
      default-zone: http://localhost:8761

  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int}

server:
  port: 0

spring:
  application:
    name: service-server
